services:
  database_pg:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db_sunny
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend_laravel:
    build: ./backend_laravel
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend_laravel:/app
    environment:
      DB_HOST: database_pg
      DB_PORT: 5432
      DB_DATABASE: db_sunny
      DB_USERNAME: admin
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database_pg

  service_node:
    image: node:20-alpine
    build: ./node_app
    ports:
      - "3000:3000"

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database_pg

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sunny.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - database_pg

volumes:
  pg_data:
