services:
  database_pg:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db_sunny
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "NieR:Automata"
    ports:
      - "5433:5432"

  backend_laravel:
    build: ./backend_laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend_laravel:/app
    environment:
      DB_HOST: database_pg
      DB_PORT: 5432
      DB_DATABASE: db_sunny
      DB_USERNAME: admin
      DB_PASSWORD: "NieR:Automata"
    depends_on:
      - database_pg

  service_node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./node_app:/app
    command: sh -c "npm init -y && npm install express && node index.js"
    ports:
      - "3000:3000"
